#!/bin/sh

setxkbmap -option srvrkeys:none

start-pulseaudio-x11

for SINK in `pactl list-sinks | grep 'index:' | cut -b12-`
do
  pactl set-sink-volume $SINK 100%
done

cd /opt/os.js && npm run serve >> /tmp/osjs.log &

while ! nc -z localhost 8000; do   
  sleep 0.1
done

electron2 /opt/launcher.js
